version: '3.7'

services:
  postgres:
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'db'
      PGPORT: '5432'
    networks:
      - service_network
    ports:
      - '5432:5432'
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: on-failure
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready' ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  service_network:
    driver: bridge
